version: "3.9"

name: ai-readme-generator-postgres

services:
  # This is your local Postgres database instance
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ai-readme-generator
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - ai-readme-generator-data:/var/lib/postgresql/data
    ports:
      - "5153:5432" # Access the DB at port 5153

  # Use Adminer to quickly view the database at localhost:2941
  adminer:
    image: adminer
    restart: always
    ports:
      - "2941:8080"

volumes:
  ai-readme-generator-data:
    driver: local
